### PR TITLE
fix(3197): fix youki version command Part of Enhancing Compatibility with runc

### LINKED ISSUE #3197: youki version command
Part of [Enhancing Compatibility with runc](https://github.com/youki-dev/youki/issues/3178)

The short `version` command for `youki` is different from that of `runc`.

youki 
The "v" is capitalized.
```
$ youki -V
youki version 0.5.4
commit: 0.5.4-0-6a1a32a624e526ff9e69eee5bf48a1b7347cd6d9

$ youki -v
error: unexpected argument '-v' found

Usage: youki [OPTIONS] <COMMAND>

For more information, try '--help'.
```

runc
```
$ runc -v
runc version 1.3.0-rc.1+dev
commit: v1.3.0-rc.1-153-gb04031d7
spec: 1.2.1
go: go1.23.0
libseccomp: 2.5.5
```

### PR DESCRIPTION
**Pull request by tommady**
## Description

Fix Youki version command
This is Part of Enhancing Compatibility with runc

## Type of Change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring (no functional changes)
- [ ] Performance improvement
- [ ] Test updates
- [ ] CI/CD related changes
- [ ] Other (please describe):

## Testing

- [ ] Added new unit tests
- [ ] Added new integration tests
- [x] Ran existing test suite
- [x] Tested manually (please provide steps)

```bash
./target/debug/youki -v                                                                                                                                  
youki version: 0.5.4                                                                                                                                          
commit: 0.5.4-81806f8a9175bbed7cb176cb66f527ff89a187ac    
```

## Related Issues

Fixes #3197

### CODE REVIEW

**Comment by utam0k** [comment]
@saku3 May I ask you to review this P?

**Comment by saku3** [comment]
Sure!

File: crates/youki/src/main.rs [hunk 1]
```diff
@@ -145,10 +138,13 @@ fn main() -> Result<()> {
             CommonCmd::Update(update) => commands::update::update(update, root_path),
         },
 
-        SubCommand::Info(info) => commands::info::info(info),
-        SubCommand::Completion(completion) => {
+        Some(SubCommand::Info(info)) => commands::info::info(info),
+        Some(SubCommand::Completion(completion)) => {
             commands::completion::completion(completion, &mut app)
         }
+        None => Opts::command()
```
Comment (saku3) [inline crates/youki/src/main.rs]:
```suggestion
        None => app.print_help().map_err(|e| anyhow::anyhow!(":{e}"))
```

**Comment by saku3** [comment]
Thanks. I think this modification looks good.

File: crates/youki/src/commands/info.rs [hunk 2]
```diff
@@ -26,10 +26,14 @@ pub fn info(_: Info) -> Result<()> {
     Ok(())
 }
 
-/// print Version of Youki
+/// print Version of Youki in Moby compatible format
```
Comment (utam0k) [inline crates/youki/src/commands/info.rs:29]: Don't remove the reference.
https://github.com/moby/moby/blob/65cc84abc522a564699bb171ca54ea1857256d10/daemon/info_unix.go#L280

**Comment by utam0k** [comment]
Could you add the tests to keep this compatibility with runc?

File: crates/youki/src/commands/info.rs (hunk 2 above)
Comment (tommady) [reply crates/youki/src/commands/info.rs:29]: Added the link you provided.

**Comment by tommady** [comment]
> Could you add the tests to keep this compatibility with runc?

sorry I am not quite sure how, could you guide me?

I thought the issue's goal is to let youki accept `-v` instead of `-V`

**Comment by YJDoc2** [comment]
>sorry I am not quite sure how, could you guide me?
> I thought the issue's goal is to let youki accept -v instead of -V

Hey, so that is correct, utam0k is asking to add test, so we can be safe against regression with this. The test for this would be running youki with `-v`  . So  in the test we can run the youki with `-v` flag and make sure that it does not error, and if we want the o/p in a certain format, we can also check that. Currently the best place for this kind of test would be in the e2e tests, but this seems a bit out-of-context for that (e2e are focused on behavioral , this seems more like an interface test) . Maybe for now we can have a simple sh script like what we have for rootless podman test, and check in that?

Also do should we support `-V` as well for backward compatibility?
Can you add a comment in code for why we set `disable_version_flag=true` ?

Thanks :)

**Comment by tommady** [comment]
> >sorry I am not quite sure how, could you guide me?
> 
> > I thought the issue's goal is to let youki accept -v instead of -V
> 
> 
> 
> Hey, so that is correct, utam0k is asking to add test, so we can be safe against regression with this. The test for this would be running youki with `-v`  . So  in the test we can run the youki with `-v` flag and make sure that it does not error, and if we want the o/p in a certain format, we can also check that. Currently the best place for this kind of test would be in the e2e tests, but this seems a bit out-of-context for that (e2e are focused on behavioral , this seems more like an interface test) . Maybe for now we can have a simple sh script like what we have for rootless podman test, and check in that?
> 
> 
> 
> Also do should we support `-V` as well for backward compatibility?
> 
> Can you add a comment in code for why we set `disable_version_flag=true` ?
> 
> 
> 
> Thanks :)

I think you’ve highlighted two key points:
	1.	Should we maintain backward compatibility?
	2.	What should the testing strategy be?

These two directly affect your suggestions:
	1.	For e2e, shell script, and interface tests, they all rely on exact output matching. Without that, we lack a clear criterion for validation. However, I believe that level of thoroughness goes beyond the scope of this issue.
	2.	Regarding the disable_version_flag=true comment—whether or not we add it depends on the decision about backward compatibility.
	•	If we decide to support backward compatibility, the comment might not be necessary.
	•	If we don’t, this becomes a breaking change and should be mentioned in the release notes.
	•	Also, since it’s a Clap-only argument, I assumed it was already documented sufficiently.

In any case, I think we should keep this PR simple and focused, as requested by the original issue.

**Comment by utam0k** [comment]
> 1. Should we maintain backward compatibility?

In my opinion, we don't need backward compatibility in this case. Not many people currently depend on this behavior.

> 2. What should the testing strategy be?

After reading YJDoc's comments, I reconsidered. I don't think it's necessary to test using new methods. I vote against no testing.

**Comment by tommady** [comment]
> > 1. Should we maintain backward compatibility?
> 
> In my opinion, we don't need backward compatibility in this case. Not many people currently depend on this behavior.
> 
> > 2. What should the testing strategy be?
> 
> After reading YJDoc's comments, I reconsidered. I don't think it's necessary to test using new methods. I vote against no testing.

Do you think the manual test is OK for you?

**Comment by utam0k** [comment]
> Do you think the manual test is OK for you?

Yes, I think, but wait for @YJDoc2

**Comment by YJDoc2** [comment]
Hey, I'm also fine with manual test for this.
